### PR TITLE
[core] passing full fieldset for verification

### LINKED ISSUE #496: Cannot verify results when using readallfields and dataintegrity
With these configurations:
```
readallfields=true
dataintegrity=true
```
the results of read operations cannot be verified correctly and so the VERIFY measurements are outputting 2000.

This is because if readallfields is false, the field set passed to the DB's read operation remains empty: https://github.com/brianfrankcooper/YCSB/blob/master/core/src/main/java/com/yahoo/ycsb/workloads/CoreWorkload.java#L640-L650. In the verifyRow method if the given cells map is empty then the result is DATA_INT_UNEXPECTED_NULL (2000): https://github.com/brianfrankcooper/YCSB/blob/master/core/src/main/java/com/yahoo/ycsb/workloads/CoreWorkload.java#L608.

### PR DESCRIPTION
**Pull request by kruthar**
When dataintegrity and readallfields are both true, pass the full field
set to db.read() so that the field values can be verified.

Fixes #496

### CODE REVIEW

File: core/src/main/java/com/yahoo/ycsb/workloads/CoreWorkload.java [hunk 1]
```diff
@@ -637,7 +637,10 @@ public void doTransactionRead(DB db)
 
 			fields=new HashSet<String>();
 			fields.add(fieldname);
-		}
+		} else if (dataintegrity) {
+      // pass the full field list if dataintegrity is on for verification
+      fields = new HashSet<String>(fieldnames);
```
Comment (cmccoy) [inline core/src/main/java/com/yahoo/ycsb/workloads/CoreWorkload.java]: This indentation looks off...

Comment (kruthar) [inline core/src/main/java/com/yahoo/ycsb/workloads/CoreWorkload.java]: Yes. The issue is that line 640 (along with a mix of other lines) has tabs instead of spaces. In a configured IDE you cant tell, but looks like Github uses different spaces/tab. This should get fixed when the checkstyle change for core goes through. Didn't want to mix in any style changes.
