### PR TITLE
[orientdb] put db conn stuff in sync method

### LINKED ISSUE #571: [orientdb] fails with multiple threads when database does not already exists
I tested with:

```bin/ycsb load orientdb -P workloads/workloada -p orientdb.url=plocal:ycsb -threads 2```

my database did not already exists and I recieived this:

```
OrientDB database not found, create fresh db
OrientDB database not found, create fresh db
Could not initialize OrientDB connection pool for Loader: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database 'ycsb'
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database 'ycsb'
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:452)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:361)
	at com.yahoo.ycsb.db.OrientDBClient.init(OrientDBClient.java:98)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:77)
	at com.yahoo.ycsb.ClientThread.run(Client.java:289)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot create new storage 'plocal:ycsb' because it is not closed
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:263)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:113)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:383)
	... 4 more
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
com.orientechnologies.orient.core.exception.ODatabaseException: Database 'plocal:ycsb' is closed
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkOpeness(ODatabaseDocumentTx.java:2930)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getMetadata(ODatabaseDocumentTx.java:793)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getMetadata(ODatabaseDocumentTx.java:121)
	at com.orientechnologies.orient.core.record.impl.ODocument.setClassName(ODocument.java:1958)
	at com.orientechnologies.orient.core.record.impl.ODocument.<init>(ODocument.java:184)
	at com.yahoo.ycsb.db.OrientDBClient.insert(OrientDBClient.java:140)
	at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:208)
	at com.yahoo.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:578)
	at com.yahoo.ycsb.ClientThread.run(Client.java:346)
```

Looks like the ```init()``` on both threads are trying to create the database. Subsequent runs of the same load command are successful because the database was created.

### PR DESCRIPTION
**Pull request by kruthar**
All db connection and creation logic is the same, it is just pulled into
a synchronized method so that multiple threads run through the
connection process one at a time.

Fixes #571

### CODE REVIEW

File: orientdb/src/main/java/com/yahoo/ycsb/db/OrientDBClient.java [hunk 1]
```diff
@@ -80,30 +80,26 @@
   private static final String ORIENTDB_MASSIVEREAD = "massiveread";
   private static final String ORIENTDB_NOCACHE = "nocache";
 
-  private final Logger log = LoggerFactory.getLogger(getClass());
-
-  @Override
-  public void init() throws DBException {
-    Properties props = getProperties();
+  private static final Logger LOG = LoggerFactory.getLogger(OrientDBClient.CLASS);
```
Comment (busbey) [inline orientdb/src/main/java/com/yahoo/ycsb/db/OrientDBClient.java]: Should this be a lower case ".class"?

File: orientdb/src/main/java/com/yahoo/ycsb/db/OrientDBClient.java [hunk 2]
```diff
@@ -80,30 +80,26 @@
...
 
+  private static synchronized ODatabaseDocumentTx initDB(Properties props) throws DBException {
```
Comment (busbey) [inline orientdb/src/main/java/com/yahoo/ycsb/db/OrientDBClient.java]: Please add javadoc explaining why this needs to be synchronized (it's not obvious because the various clients don't appear to share connection objects).

I think it's because of the automatic table creation?

File: orientdb/src/main/java/com/yahoo/ycsb/db/OrientDBClient.java (hunk 1 above)
Comment (kruthar) [inline orientdb/src/main/java/com/yahoo/ycsb/db/OrientDBClient.java]: Nice catch. OrientDBClient.CLASS="usertable".

File: orientdb/src/main/java/com/yahoo/ycsb/db/OrientDBClient.java (hunk 2 above)
Comment (kruthar) [inline orientdb/src/main/java/com/yahoo/ycsb/db/OrientDBClient.java]: done

**Comment by risdenk** [comment]
Would there be issues here if multiple YCSB clients are run at once? This will only help fix multiple threads in one client correct?

Does the initdb need to create the db? Is it possible to make it necessary to have the db already exist as a prerequisite? Like the other bindings ie: Solr and Cassandra

**Comment by busbey** [comment]
We could add a note to the README for the folks who use multiple Client invocations, letting them know how to create it in advance?

**Comment by kruthar** [comment]
@risdenk 

>Would there be issues here if multiple YCSB clients are run at once? This will only help fix multiple threads in one client correct?

Correct.

> Does the initdb need to create the db? Is it possible to make it necessary to have the db already exist as a prerequisite? Like the other bindings ie: Solr and Cassandra

So, the OrientDB client is the only one that I am aware of that actually creates a database for you. All others require it to be present. I kept this functionality because it was there from the initial creation of the client. I'm ok with removing it, or just writing a note about that specific scenario.

**Comment by busbey** [comment]
Either a note or removal sounds fine by me.

Could also move the creation into a utility class that the README references. I think I've seen a couple of those.

**Comment by kruthar** [comment]
I decided to keep the db creation functionality in place since 1) it works and 2) mongodb does "create" a database if it doesn't already exist, although in a much more passive way.

I added a note about it to the README

**Comment by busbey** [comment]
+1
